###
GET http://localhost:8080/users
Authorization: Basic test 123qwe
###
GET http://localhost:8080/users/2
Authorization: Basic test 123qwe
###
### Send POST request with json body
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic test 123qwe

{
  "name": "Dima",
  "birthDate": "1986-11-11T21:12:12.054+0000"
}

###
DELETE http://localhost:8080/users/2
Authorization: Basic test 123qwe